//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGWP.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ggwpDBEntities : DbContext
    {
        public ggwpDBEntities()
            : base("name=ggwpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Igra> Igra { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<KorisnikTim> KorisnikTim { get; set; }
        public virtual DbSet<Raspored> Raspored { get; set; }
        public virtual DbSet<Tim> Tim { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vijesti> Vijesti { get; set; }
    }
}
