//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGWP.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspored
    {
        public int id { get; set; }
        public int tim1_id { get; set; }
        public int tim2_id { get; set; }
        public System.DateTime datum { get; set; }
        public string tip { get; set; }
        public string rezultat { get; set; }
    
        public virtual Tim Tim { get; set; }
        public virtual Tim Tim1 { get; set; }
    }
}
