//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGWP.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vijesti
    {
        public int id { get; set; }
        public string naslov { get; set; }
        public System.DateTime datum { get; set; }
        public string tekst { get; set; }
        public int status { get; set; }
    }
}
